### ISSUE TITLE
Undefined properties and other things discovered by static analysis

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/Edit-Flow#518]
`phpstan.neon.dist`

```yaml
includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/edit_flow.php
        - %currentWorkingDirectory%/common/
        - %currentWorkingDirectory%/modules/
    autoload_files:
        - %currentWorkingDirectory%/edit_flow.php
        - %currentWorkingDirectory%/common/php/util.php
        - %currentWorkingDirectory%/common/php/class-module.php
        - %currentWorkingDirectory%/common/php/trait-block-editor-compatible.php
        - %currentWorkingDirectory%/common/php/screen-options.php
        # Modules
        - %currentWorkingDirectory%/modules/user-groups/user-groups.php
        - %currentWorkingDirectory%/modules/editorial-comments/editorial-comments.php
        - %currentWorkingDirectory%/modules/dashboard/widgets/dashboard-notepad.php
        - %currentWorkingDirectory%/modules/dashboard/dashboard.php
        - %currentWorkingDirectory%/modules/notifications/notifications.php
        - %currentWorkingDirectory%/modules/calendar/calendar.php
        - %currentWorkingDirectory%/modules/settings/settings.php
        - %currentWorkingDirectory%/modules/custom-status/custom-status.php
        - %currentWorkingDirectory%/modules/custom-status/compat/block-editor.php
        - %currentWorkingDirectory%/modules/story-budget/story-budget.php
        - %currentWorkingDirectory%/modules/editorial-metadata/editorial-metadata.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with [34567] parameters, 2 required\.$#'
        - '#^Function do_action invoked with [3456] parameters, 1-2 required\.$#'
        - '#^Function current_user_can invoked with 2 parameters, 1 required\.$#'
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```

`composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress`

and

`vendor/bin/phpstan analyze -l 0` Levels go up to 7.

On Level 0: "[ERROR] Found 212 errors" see https://gist.github.com/szepeviktor/595101e84d27d8a9b451faf8b304133d

What do you think?
